### PR TITLE
11.6.0-android

### PR DESCRIPTION
**Pull request by avaer**

### CODE REVIEW

**Comment by avaer** [comment]
This should be compiling up to NDK linkage:

```
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `initAssetManager':                                                                                                                                
android_file.cc:(.text+0x8): undefined reference to `AAssetManager_fromJava'                                                                                                                                                            
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_access':                                                                                                                                  
android_file.cc:(.text+0xe8): undefined reference to `AAssetManager_open'                                                                                                                                                               
android_file.cc:(.text+0xf0): undefined reference to `AAsset_close'                                                                                                                                                                     
android_file.cc:(.text+0x10c): undefined reference to `AAssetManager_openDir'                                                                                                                                                           
android_file.cc:(.text+0x114): undefined reference to `AAssetDir_close'                                                                                                                                                                 
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_close':                                                                                                                                   
android_file.cc:(.text+0x278): undefined reference to `AAsset_close'                                                                                                                                                                    
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_copyfile':                                                                                                                                
android_file.cc:(.text+0x330): undefined reference to `uv__fs_copyfile(uv_fs_s*)'                                                                                                                                                       
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_fdatasync':                                                                                                                               
android_file.cc:(.text+0x4e8): undefined reference to `uv__fs_fdatasync(uv_fs_s*)'                                                                                                                                                      
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_fstat':                                                                                                                                   
android_file.cc:(.text+0x570): undefined reference to `uv__fs_fstat(int, uv_stat_t*)'                                                                                                                                                   
android_file.cc:(.text+0x57c): undefined reference to `AAsset_getLength64'                                                                                                                                                              
android_file.cc:(.text+0x5f4): undefined reference to `AAssetManager_openDir'                                                                                                                                                           
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_fsync':                                                                                                                                   
android_file.cc:(.text+0x6a8): undefined reference to `uv__fs_fsync(uv_fs_s*)'                                                                                                                                                          
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_futime':                                                                                                                                  
android_file.cc:(.text+0x784): undefined reference to `uv__fs_futime(uv_fs_s*)'                                                                                                                                                         
/home/a/node-magicleap/out/Release/obj.target/libnode.a(android_file.o): In function `android_lstat':                                                                                                                                   
android_file.cc:(.text+0x800): undefined reference to `uv__fs_lstat(char const*, uv_stat_t*)'                                                                                                                                           
android_file.cc:(.text+0x818): undefined reference to `AAssetManager_open'                                                                                                                                                              
android_file.cc:(.text+0x8ac): undefined reference to `AAssetManager_openDir'                                                                                                                                                           
android_file.cc:(.text+0x9cc): undefined reference to `AAsset_close'                                                                                                                                                                    
android_file.cc:(.text+0xaa0): undefined reference to `AAssetDir_close'
```

**Comment by avaer** [comment]
Fixed the interal linkage errors; the only think left to do here is to link against an NDK:
```
/home/a/node-magicleap/out/Release/obj.target/deps/uv/libuv.a(android_file.o): In function `initAssetManager':
/home/a/node-magicleap/out/../deps/uv/src/android_file.c:5: undefined reference to `AAssetManager_fromJava' 
/home/a/node-magicleap/out/Release/obj.target/deps/uv/libuv.a(android_file.o): In function `android_access':
/home/a/node-magicleap/out/../deps/uv/src/android_file.c:36: undefined reference to `AAssetManager_open'    
/home/a/node-magicleap/out/../deps/uv/src/android_file.c:38: undefined reference to `AAsset_close'          
/home/a/node-magicleap/out/../deps/uv/src/android_file.c:41: undefined reference to `AAssetManager_openDir' 
/home/a/node-magicleap/out/../deps/uv/src/android_file.c:43: undefined reference to `AAssetDir_close'   
```

**Comment by vyrnix9582046173** [comment]
Fixed above errors by linking android lib in 2337242

**Comment by avaer** [comment]
This should include all necessary filesystem and dlib hacks for an android APK-loaded node experience.

**Pull request closed without merging**
